# Generated by Django 5.2.4 on 2025-07-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Numéro généré automatiquement', max_length=30, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant HT en euros', max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=20.0, help_text='Taux de TVA en %', max_digits=5)),
                ('montant_ttc', models.DecimalField(blank=True, decimal_places=2, help_text='Montant TTC calculé automatiquement', max_digits=10, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('payee', models.BooleanField(default=False, verbose_name='Payée')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='factures.categorie')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clients.client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(default='Création', max_length=50)),
                ('facture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factures.facture')),
            ],
        ),
    ]
