# Generated by Django 5.2.4 on 2025-07-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_facture_client_alter_facture_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='payee',
            field=models.BooleanField(default=False),
        ),
    ]
