# Generated by Django 5.2.4 on 2025-07-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_facture_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='montant_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant TTC calculé automatiquement', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Taux de TVA en %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='facture',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='factures.categorie'),
        ),
    ]
